name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+**'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch source code
        uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch source code
        uses: actions/checkout@v2
      - name: Use Node.js 16.15.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.0
      - name: Check NPM version
        run: npm -v
      - name: Check Node version
        run: node -v
      - name: Install rust deps and hc-cli
        run: ./scripts/install-hc-tools.sh
      - name: Install workspace dependencies
        run: nix-shell --run "pnpm run install-deps"
      - name: Build happ
        run: |
          nix-shell --run "pnpm run happ-pack"
      - name: Build webhApp
        run: |
          nix-shell --run "pnpm run webhapp-pack"
      - name: upload webhapp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${GITHUB_REF#refs/tags/}" "workdir/rea-playspace.webhapp" --clobber
