name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+**'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch source code
        uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch source code
        uses: actions/checkout@v2
      - name: Use Node.js 16.15.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.0
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.22.2
      - name: Check npm version
        run: npm -v
      - name: Check Node version
        run: node -v
      - name: Check pnpm version
        run: pnpm -v  
      - name: Install hc tool and wasm target
        shell: bash # important because this runs shell scripts
        run: |
          npm run hc-install
      - name: Cache cargo    
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}      
      - name: Install workspace dependencies
        run: pnpm run install-deps
      - name: Build happ
        run: pnpm run happ-pack
      - name: Build webhApp
        run: pnpm run webhapp-pack
      - name: upload webhapp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${GITHUB_REF#refs/tags/}" "workdir/rea-playspace.webhapp" --clobber
